apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: go-component-sample
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: go-component-sample
    app.kubernetes.io/part-of: go-application-sample
  name: go-component-sample
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: go-app
      app.kubernetes.io/instance: go-component-sample
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: go-app
        app.kubernetes.io/instance: go-component-sample
    spec:
      containers:
      - image: quay.io/nafta_org/test2/go-application-sample/go-component-sample@sha256:83c8af40273034f9afea0f891de1b5347b30cd90d19ef83f1f57998da4a84289
        name: my-go
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          requests:
            cpu: 10m
            memory: 10Mi
status: {}
